### ISSUE TITLE
Add possibility to select file, not only drag & drop

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Images#3]

**Comment by andwah** [comment]
Just a little note,It is also possible to paste (CTRL+V) an image.

**Comment by miyconst** [comment]
@andwah how should it works? I could not create an image by CTRL + V, also can't paste an image of the People/Person page.

**Comment by andwah** [comment]
I have not tested to paste an image for a long time, maybe it stopped working..

i think you need to copy the image data into the clipboard (not to reference/path to the image). 

btw, this functionallity is in the ```<juicy-filedrop>``` element https://github.com/Juicy/juicy-filedrop

**Comment by miyconst** [comment]
@andwah I have added possibility to select files, not only Drag & Drop, should I also update
https://github.com/Juicy/juicy-filedrop repo?

**Comment by andwah** [comment]
do you think it's better to create a new element that "wrapps" the juicy-filedrop element that has the "select file" function?

**Comment by miyconst** [comment]
@andwah I think it is better to wrap everything inside juicy-filedrop element. I could not imagine a website or a webpage where only file drag & drop without file selecting would be needed.

Anyway it is very easy to disable the `select file` feature, if someone really wants to.

**Comment by andwah** [comment]
one case can be if you have two (or more) drop zones on a page and you move images between them,, then you dont need a "select file" feature..

**Comment by andwah** [comment]
but in that case we may have a flag that disables that feature..

**Comment by miyconst** [comment]
So, should I merge it to `juicy-filedrop`?

**Comment by miyconst** [comment]
Merged to `juicy-filedrop` repo.
https://github.com/Juicy/juicy-filedrop/commit/599463a35d4719e00725250f09ccf3324a5713dc
